//! Proof metadata and level tracking for the wPoA+STARK system.
//!
//! Tracks the proving tier of each STARK proof associated with a block:
//!
//! | Level | Name | Description |
//! |-------|------|-------------|
//! | L0 | Sync | Inline proof generated synchronously during `produce_block`. Blocks and proving are coupled. |
//! | L1 | Async | Proof generated asynchronously after block sealing (by proposer or standalone Prover). |
//! | L2 | Recursive | L1 proofs aggregated into a recursive STARK covering multiple blocks. |
//!
//! ## Lifecycle
//!
//! ```text
//! Sealed ──► L1-pending ──► L1-proven ──► (aggregate) ──► L2-aggregated
//!                     └──► Challenged ──► Slashed/Reverted
//! ```
//!
//! `ProofMetadata` is stored per-block in a dedicated store and queried by
//! the consensus and prover subsystems to drive proving decisions.

use serde::{Deserialize, Serialize};

use shell_primitives::Address;

// ── ProofLevel ────────────────────────────────────────────────────────────────

/// The tier of STARK proof covering a block.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
pub enum ProofLevel {
    /// No proof yet — block is sealed but unproven.
    #[default]
    None,
    /// L0: synchronous proof generated inline during `produce_block`.
    ///
    /// This is the legacy mode (current C2/C3 path). Proof is embedded
    /// in the block header (`sig_aggregate_proof`). Block production is
    /// blocked until proving completes.
    Sync,
    /// L1: asynchronous single-block proof, attached via `ProofAmendment`.
    ///
    /// Block is sealed without a proof; proof arrives later via P2P gossip.
    Async,
    /// L2: recursive aggregate proof covering multiple blocks.
    ///
    /// Generated by the aggregation scheduler (J3) from a window of L1 proofs.
    Recursive,
}

impl ProofLevel {
    /// Returns true if the block has any covering proof (L0/L1/L2).
    pub fn is_proven(self) -> bool {
        !matches!(self, ProofLevel::None)
    }

    /// Returns true if this proof can be stripped (sigs removed from block body).
    ///
    /// Stripping requires at least an async L1 proof or higher.
    pub fn allows_sig_stripping(self) -> bool {
        matches!(self, ProofLevel::Async | ProofLevel::Recursive)
    }

    /// Returns the numeric level (0 = None, 1 = Sync, 2 = Async, 3 = Recursive).
    pub fn as_u8(self) -> u8 {
        match self {
            ProofLevel::None => 0,
            ProofLevel::Sync => 1,
            ProofLevel::Async => 2,
            ProofLevel::Recursive => 3,
        }
    }

    /// Parse from a u8 level.
    pub fn from_u8(v: u8) -> Self {
        match v {
            1 => ProofLevel::Sync,
            2 => ProofLevel::Async,
            3 => ProofLevel::Recursive,
            _ => ProofLevel::None,
        }
    }

    /// Human-readable label.
    pub fn as_str(self) -> &'static str {
        match self {
            ProofLevel::None => "none",
            ProofLevel::Sync => "sync-L0",
            ProofLevel::Async => "async-L1",
            ProofLevel::Recursive => "recursive-L2",
        }
    }
}

// ── ProofMetadata ─────────────────────────────────────────────────────────────

/// Proof status and attribution metadata for a single block.
///
/// Stored by the node alongside the block, updated as the proof pipeline
/// progresses.  Consulted by:
/// - `ProofBacklog` (G1): to decide which blocks still need proofs
/// - Block state machine (K2): to drive `Sealed → Proven → Stripped` transitions
/// - Challenge handler (I2): to record disputed and resolved proofs
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProofMetadata {
    /// Protocol version.
    pub version: u8,
    /// Block height this metadata covers.
    pub block_number: u64,
    /// Current proof level.
    pub level: ProofLevel,
    /// Address of the prover that submitted the proof (None if `level` is None or Sync).
    ///
    /// For L0 (Sync) proofs, the prover is always the block proposer and this
    /// field is left None to save space.
    pub prover: Option<Address>,
    /// Unix timestamp (seconds) when the proof was accepted.
    pub proved_at: Option<u64>,
    /// Whether the proof has been challenged.
    pub challenged: bool,
    /// Whether the proof has been verified by the challenge resolution process.
    pub challenge_resolved: bool,
    /// Whether signatures have been stripped from this block.
    pub sigs_stripped: bool,
    /// For L2: the block numbers covered by the recursive proof.
    ///
    /// Empty unless `level == Recursive`.
    pub aggregate_range: Option<(u64, u64)>,
}

/// Current serialization version.
pub const PROOF_METADATA_VERSION: u8 = 1;

impl ProofMetadata {
    /// Create a metadata record for a newly sealed block with no proof.
    pub fn sealed(block_number: u64) -> Self {
        Self {
            version: PROOF_METADATA_VERSION,
            block_number,
            level: ProofLevel::None,
            prover: None,
            proved_at: None,
            challenged: false,
            challenge_resolved: false,
            sigs_stripped: false,
            aggregate_range: None,
        }
    }

    /// Mark as proven at the given level by the given prover.
    ///
    /// `prover` may be `None` for L0 (sync) proofs where the proposer is implicit.
    pub fn mark_proven(&mut self, level: ProofLevel, prover: Option<Address>, timestamp_secs: u64) {
        self.level = level;
        self.prover = prover;
        self.proved_at = Some(timestamp_secs);
    }

    /// Mark as challenged.
    pub fn mark_challenged(&mut self) {
        self.challenged = true;
    }

    /// Mark the challenge as resolved (accepted or rejected).
    pub fn resolve_challenge(&mut self) {
        self.challenge_resolved = true;
    }

    /// Mark that signatures have been stripped from this block.
    pub fn mark_stripped(&mut self) {
        self.sigs_stripped = true;
    }

    /// Whether this block is eligible for signature stripping.
    pub fn can_strip(&self) -> bool {
        self.level.allows_sig_stripping()
            && !self.sigs_stripped
            && (!self.challenged || self.challenge_resolved)
    }

    /// Serialize to JSON bytes for storage.
    pub fn to_json(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }

    /// Deserialize from JSON bytes.
    pub fn from_json(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }
}

// ── ProofMetadataStore ────────────────────────────────────────────────────────

/// Key prefix for proof metadata in the key-value store.
///
/// Full key: `pm/` + block_number (8 bytes big-endian).
/// Using block_number (not hash) so range scans work correctly.
pub const PROOF_METADATA_KEY_PREFIX: &[u8] = b"pm/";

/// Build a storage key for proof metadata.
pub fn proof_metadata_key(block_number: u64) -> Vec<u8> {
    let mut key = PROOF_METADATA_KEY_PREFIX.to_vec();
    key.extend_from_slice(&block_number.to_be_bytes());
    key
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn proof_level_ordering() {
        assert!(ProofLevel::None < ProofLevel::Sync);
        assert!(ProofLevel::Sync < ProofLevel::Async);
        assert!(ProofLevel::Async < ProofLevel::Recursive);
    }

    #[test]
    fn proof_level_is_proven() {
        assert!(!ProofLevel::None.is_proven());
        assert!(ProofLevel::Sync.is_proven());
        assert!(ProofLevel::Async.is_proven());
        assert!(ProofLevel::Recursive.is_proven());
    }

    #[test]
    fn proof_level_sig_stripping() {
        assert!(!ProofLevel::None.allows_sig_stripping());
        assert!(!ProofLevel::Sync.allows_sig_stripping());
        assert!(ProofLevel::Async.allows_sig_stripping());
        assert!(ProofLevel::Recursive.allows_sig_stripping());
    }

    #[test]
    fn proof_level_roundtrip_u8() {
        for level in [
            ProofLevel::None,
            ProofLevel::Sync,
            ProofLevel::Async,
            ProofLevel::Recursive,
        ] {
            assert_eq!(ProofLevel::from_u8(level.as_u8()), level);
        }
    }

    #[test]
    fn proof_level_str_labels() {
        assert_eq!(ProofLevel::None.as_str(), "none");
        assert_eq!(ProofLevel::Sync.as_str(), "sync-L0");
        assert_eq!(ProofLevel::Async.as_str(), "async-L1");
        assert_eq!(ProofLevel::Recursive.as_str(), "recursive-L2");
    }

    #[test]
    fn proof_metadata_sealed_defaults() {
        let m = ProofMetadata::sealed(10);
        assert_eq!(m.block_number, 10);
        assert_eq!(m.level, ProofLevel::None);
        assert!(!m.challenged);
        assert!(!m.sigs_stripped);
        assert!(!m.can_strip());
    }

    #[test]
    fn proof_metadata_mark_proven_async() {
        let mut m = ProofMetadata::sealed(5);
        m.mark_proven(ProofLevel::Async, Some(Address::from([0x01; 20])), 1_700_000_100);
        assert_eq!(m.level, ProofLevel::Async);
        assert!(m.can_strip());
        m.mark_stripped();
        assert!(!m.can_strip());
        assert!(m.sigs_stripped);
    }

    #[test]
    fn proof_metadata_challenge_blocks_stripping() {
        let mut m = ProofMetadata::sealed(7);
        m.mark_proven(ProofLevel::Async, None, 0);
        m.mark_challenged();
        assert!(!m.can_strip()); // challenged → blocked
        m.resolve_challenge();
        assert!(m.can_strip()); // resolved → allowed
    }

    #[test]
    fn proof_metadata_json_roundtrip() {
        let mut m = ProofMetadata::sealed(99);
        m.mark_proven(ProofLevel::Recursive, Some(Address::from([0xAB; 20])), 9999);
        m.aggregate_range = Some((90, 99));
        let json = m.to_json().unwrap();
        let decoded = ProofMetadata::from_json(&json).unwrap();
        assert_eq!(m, decoded);
    }

    #[test]
    fn proof_metadata_key_format() {
        let key = proof_metadata_key(42);
        assert!(key.starts_with(PROOF_METADATA_KEY_PREFIX));
        assert_eq!(key.len(), PROOF_METADATA_KEY_PREFIX.len() + 8);
    }

    #[test]
    fn proof_metadata_keys_are_ordered_by_block_number() {
        let k10 = proof_metadata_key(10);
        let k20 = proof_metadata_key(20);
        assert!(k10 < k20);
    }
}
