use shell_core::{AccessListItem, Transaction};
use shell_primitives::{Address, Bytes, ShellHash, U256};

#[test]
fn sdk_hash_transaction_golden_vector_matches_chain() {
    let tx = Transaction {
        chain_id: 1337,
        nonce: 7,
        to: Some(Address::from([0x11; 20])),
        value: U256::from(0x1234u64),
        data: Bytes::from(vec![0xde, 0xad, 0xbe, 0xef]),
        gas_limit: 50_000,
        max_fee_per_gas: 1_000_000_000,
        max_priority_fee_per_gas: 250_000_000,
        access_list: Some(vec![AccessListItem {
            address: Address::from([0x22; 20]),
            storage_keys: vec![ShellHash::from([0x33; 32]), ShellHash::from([0x44; 32])],
        }]),
        tx_type: 3,
        max_fee_per_blob_gas: Some(0),
        blob_versioned_hashes: Some(vec![ShellHash::from([0x55; 32])]),
    };

    // Generated by shell-sdk hashTransaction():
    // 0xcc9b2cfd55bb83205daeb92128de039380fed2ae3ec36b07cfbecb80ade19f4c
    let expected = ShellHash::from([
        0xcc, 0x9b, 0x2c, 0xfd, 0x55, 0xbb, 0x83, 0x20, 0x5d, 0xae, 0xb9, 0x21, 0x28, 0xde, 0x03,
        0x93, 0x80, 0xfe, 0xd2, 0xae, 0x3e, 0xc3, 0x6b, 0x07, 0xcf, 0xbe, 0xcb, 0x80, 0xad, 0xe1,
        0x9f, 0x4c,
    ]);

    assert_eq!(tx.hash(), expected);
}
